import { Candidate } from '../types';

export const MOCK_CANDIDATES: Candidate[] = [
  {
    id: 'c1',
    maskedId: '8842',
    experienceYears: 10,
    rating: 5.0,
    reviewCount: 12,
    agencyName: 'Sunlight Agency',
    nationality: 'Filipino',
    availability: 'Immediate',
    isPrivacyMode: true,
    locationMasked: true,
    phoneMasked: true,
    agencyPhone: '+852 2345 6789',
    agencyEmail: 'contact@sunlight.com',
    estimatedCost: 'HK$ 12,800',
    skills: [
      { name: 'Elderly Care', icon: 'heart', verified: true },
      { name: 'CPR Certified', icon: 'cross', verified: true },
      { name: 'Cantonese Cooking', icon: 'chef', verified: true },
      { name: 'Fluent Cantonese', icon: 'check', verified: true },
    ],
  },
  {
    id: 'c2',
    maskedId: '9901',
    experienceYears: 4,
    rating: 4.8,
    reviewCount: 5,
    agencyName: 'HelperChoice',
    nationality: 'Indonesian',
    availability: 'In 1 Month',
    isPrivacyMode: true,
    locationMasked: true,
    phoneMasked: true,
    agencyPhone: '+852 3456 7890',
    agencyEmail: 'info@helperchoice.com',
    estimatedCost: 'HK$ 9,500',
    skills: [
      { name: 'Child Care', icon: 'child', verified: true },
      { name: 'Pet Friendly', icon: 'check', verified: true },
      { name: 'English Speaking', icon: 'check', verified: true },
    ],
  },
  {
    id: 'c3',
    maskedId: '7723',
    experienceYears: 7,
    rating: 4.9,
    reviewCount: 24,
    agencyName: 'Prestige Home Care',
    nationality: 'Filipino',
    availability: 'Immediate',
    isPrivacyMode: true,
    locationMasked: true,
    phoneMasked: true,
    agencyPhone: '+852 4567 8901',
    agencyEmail: 'contact@prestige.com',
    estimatedCost: 'HK$ 15,000',
    skills: [
      { name: 'Nursing', icon: 'cross', verified: true },
      { name: 'Elderly Care', icon: 'heart', verified: true },
      { name: 'Western Cooking', icon: 'chef', verified: true },
    ],
  },
  {
    id: 'c4',
    maskedId: '5510',
    experienceYears: 2,
    rating: 4.5,
    reviewCount: 3,
    agencyName: 'Sunlight Agency',
    nationality: 'Thai',
    availability: 'Immediate',
    isPrivacyMode: true,
    locationMasked: true,
    phoneMasked: true,
    agencyPhone: '+852 2345 6789',
    agencyEmail: 'contact@sunlight.com',
    estimatedCost: 'HK$ 12,800',
    skills: [
      { name: 'General Housekeeping', icon: 'check', verified: true },
      { name: 'Thai Cooking', icon: 'chef', verified: true },
    ],
  },
  {
    id: 'c5',
    maskedId: '3392',
    experienceYears: 15,
    rating: 5.0,
    reviewCount: 40,
    agencyName: 'Elite Helpers',
    nationality: 'Filipino',
    availability: 'In 2 Months',
    isPrivacyMode: true,
    locationMasked: true,
    phoneMasked: true,
    agencyPhone: '+852 5678 9012',
    agencyEmail: 'hello@elitehelpers.com',
    estimatedCost: 'HK$ 14,200',
    skills: [
      { name: 'Newborn Care', icon: 'child', verified: true },
      { name: 'Post-natal Care', icon: 'heart', verified: true },
      { name: 'Driving', icon: 'check', verified: true },
    ],
  },
];